### ISSUE TITLE
stride tokens fail to be moved around in ibc.fun

### ISSUE THREAD

**Issue by Subfortytwo** [skip-mev/ibc-dot-fun#133]
Hi,

I am having issues to move stATOMs around, let's say from Kujira->Osmosis. I get the following error:

`console.js:36 Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: spendable balance  is smaller than 1000000stuatom: insufficient funds [!stride-!labs/cosmos-sdk@v0.47.4-stride-distribution-fix-1/x/bank/keeper/send.go:252] With gas wanted: '18446744073709551615' and gas used: '36248' : unknown request`

Needless to say that I have enough stAtom to send. I tried with Keplr and Leap, issue is the same. What I am currently doing is manually sending my st* to stride, then, from there, I can use ibc.fun to go around.

Thanks for your help.

**Comment by grikomsn** [comment]
This has been fixed! Please try again and let us know if you found any issues.
